# Big Data Processing Systems — 2020/21
## Project nº 2

### The Data Set
Consider you want to process information about taxi rides in some city to better understand the
behavior of the community and help taxi drivers maximize their profit.
To this end, you have a data set with information about taxi drivers, including information for pickup
and drop-off location.
The data set has the following columns:

| Col# | Column Name          | Type        | Description                                                          |
|------|----------------------|-------------|----------------------------------------------------------------------|
| 1    | Trip ID              | Plain Text  | A unique identifier for the trip.                                    |
|      |                      |             |                                                                      |
| 2    | Taxi ID              | Plain Text  | A unique identifier for the taxi.                                    |
|      |                      |             |                                                                      |
| 3    | Trip Start Timestamp | Date & Time | When the trip started, rounded to the nearest 15 minutes.            |
|      |                      |             |                                                                      |
| 4    | Trip End Timestamp   | Date & Time | When the trip ended, rounded to the nearest 15 minutes.              |
|      |                      |             |                                                                      |
| 5    | Trip Seconds         | Number      | Time of the trip in seconds.                                         |
|      |                      |             |                                                                      |
| 6    | Trip Miles           | Number      | Distance of the trip in miles.                                       |
|      |                      |             |                                                                      |
| 7    | Pickup Region ID     | Plain Text  | The City Region where the trip began. For privacy, this field is not |
|      |                      |             | shown for some trips.                                                |
|      |                      |             |                                                                      |
| 8    | Dropoff Region ID    | Plain Text  | The City Region where the trip ended. For privacy, this field is not |
|      |                      |             | shown for some trips.                                                |
|      |                      |             |                                                                      |
| 9    | Pickup Community     | Number      | The Community Area where the trip began. For privacy, this field     |
|      | Area                 |             | is not shown for some trips.                                         |
|      |                      |             |                                                                      |
| 10   | Dropoff Community    | Number      | The Community Area where the trip ended. For privacy, this field     |
|      | Area                 |             | is not shown for some trips.                                         |
|      |                      |             |                                                                      |
| 11   | Fare                 | Number      | The fare for the trip.                                               |
|      |                      |             |                                                                      |
| 12   | Tips                 | Number      | The tip for the trip.                                                |
|      |                      |             |                                                                      |
| 13   | Tolls                | Number      | The tolls for the trip.                                              |
|      |                      |             |                                                                      |
| 14   | Extras               | Number      | Extra charges for the trip.                                          |
|      |                      |             |                                                                      |
| 15   | Trip Total           | Number      | Total cost of the trip, the total of the previous columns.           |
|      |                      |             |                                                                      |
| 16   | Payment Type         | Plain Text  | Type of payment for the trip.                                        |
|      |                      |             |                                                                      |
| 17   | Company              | Plain Text  | The taxi company.                                                    |
|      |                      |             |                                                                      |
| 18   | Pickup Centroid      | Number      | The latitude of the center of the pickup city region or the          |
|      | Latitude             |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |
|      |                      |             |                                                                      |
| 19   | Pickup Centroid      | Number      | The longitude of the center of the pickup city region or the         |
|      | Longitude            |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |
|      |                      |             |                                                                      |
| 20   | Pickup Centroid      | Point       | The location of the center of the pickup city region or the          |
|      | Location             |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |
| 21   | Dropoff Centroid     | Number      | The latitude of the center of the dropoff city region or the         |
|      | Latitude             |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |
|      |                      |             |                                                                      |
| 22   | Dropoff Centroid     | Number      | The longitude of the center of the dropoff city region or the        |
|      | Longitude            |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |
|      |                      |             |                                                                      |
| 23   | Dropoff Centroid     | Point       | The location of the center of the dropoff city region or the         |
|      | Location             |             | community area if the city region has been omitted. For privacy,     |
|      |                      |             | this field is not shown for some trips.                              |


Please note that numbers, when larger than 999, have a coma separating the thousands, e.g., “1,345.98”.
Take this into consideration when converting the string to a number.

In [17]:
!head -3 Taxi_Trips_151MB.csv

0f7572c6b0465c8ebd4e54445e7a26a989f8e486;72fa75a736779ba1abb3fee6686254e254956acc5ac5b93964f28aa445a796164c0aa35e18b04d3ed03a6fdc010c86f95d5ac74aa76a7cfe1d3dec74f514c705;03/23/2013 11:30:00 PM;03/23/2013 11:45:00 PM;1,440;17.68;17031980000;;76;;36.25;0.00;0.00;3.00;39.25;Cash;;41.97907082;-87.903039661;POINT (-87.9030396611 41.9790708201);;;
752e99e7c9ea7f66054550d69198a623b5d2c3a7;99a94f14a88b159da4fc114046808dec7ed18abe81ab9a42828c4b1149e5dee6f5bdbc5e05c45d72c1105e9fe85b9c84ba2dffaa44dc956b751c4fd77809f631;03/28/2013 04:00:00 PM;03/28/2013 05:00:00 PM;3,120;18.6;17031320100;;32;;39.45;0.00;0.00;3.00;42.45;Credit Card;;41.884987192;-87.620992913;POINT (-87.6209929134 41.8849871918);;;
8cec5ca7cf5dfecc9f326c554ed109e3fd7218e5;5b0e845181646f6a7a9201c1edc9a7b0d4aa0fd14bf25513e85def4a880203df70c5056e5e65ad03a256ba8bab2739428a87b7e3e069ec11847b3278846857e7;01/01/2013 09:45:00 AM;01/01/2013 10:15:00 AM;1,740;13.75;17031081300;;8;;30.85;0.00;0.00;3.00;33.85;Cash;;41.898331794;-87.620762865;POINT (-87.6207628651 41.8983317935);;;

### Loading Data
We start by loading data into a data frame that will be used in all exercices

In [18]:
from pyspark import StorageLevel
from pyspark.sql import *
from pyspark.sql.types import *
from pyspark.sql.functions import *

spark = SparkSession.builder.master('local[*]') \
    .appName('Exercise').getOrCreate()

fields = [
    StructField('TripID', StringType(), True),
    StructField('TaxiID', StringType(), True),
    StructField('TripStartTimestamp', TimestampType(), True),
    StructField('TripEndTimestamp', TimestampType(), True),
    StructField('TripSeconds', DoubleType(), True),
    StructField('TripMiles', DoubleType(), True),
    StructField('PickupRegionID', StringType(), True),
    StructField('DropoffRegionID', StringType(), True),
    StructField('PickupCommunity', DoubleType(), True),
    StructField('DropoffCommunity', DoubleType(), True),
    StructField('Fare', DoubleType(), True),
    StructField('Tips', DoubleType(), True),
    StructField('Tolls', DoubleType(), True),
    StructField('Extras', DoubleType(), True),
    StructField('TripTotal', DoubleType(), True),
    StructField('PaymentType', StringType(), True),
    StructField('Company', StringType(), True),
    StructField('PickupCentroidLatitude', DoubleType(), True),
    StructField('PickupCentroidLongitude', DoubleType(), True),
    StructField('PickupCentroidLocation', StringType(), True),
    StructField('DropoffCentroidLatitude', DoubleType(), True),
    StructField('DropoffCentroidLongitude', DoubleType(), True),
    StructField('DropoffCentroidLocation', StringType(), True)]

# https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html
df = spark.read.csv('Taxi_Trips_151MB.csv', sep=';', schema=StructType(fields), timestampFormat="M/d/y h:m:s a")

### Spark Data Frames

You are asked to use Data Frames to create indexes for answering the following queries:

#### 1.	(2 points) To have a rough understanding of the fluctuation in the demand for taxis along the years, create and index reporting

How many trips were started in each year present in the data set?

In [19]:
%%time

# How many trips were started in each year present in the data set?
# (year, #trips)
df.groupBy(year("TripStartTimestamp").alias("year")) \
    .count() \
    .withColumnRenamed("count", "#trips") \
    .cache().show(truncate=False)

+----+------+
|year|#trips|
+----+------+
|2018|41567 |
|2015|64761 |
|2013|54409 |
|2014|74753 |
|2019|32797 |
|2020|6829  |
|2016|63628 |
|2017|50006 |
+----+------+

CPU times: user 3.08 ms, sys: 4.02 ms, total: 7.1 ms
Wall time: 1.69 s

#### 2.	(3 points) To have a rough understanding of the fluctuation in the demand for taxis per hour, create and index reporting
For each of the 24 hours of the day, how many taxi trips there were, what was their average trip miles and trip total cost?

Non-integer values should be printed with two decimal places.

Output is expected to have four columns (time_slot, #trips, avg_trip_miles, avg_trip_total). In the example below the values are not real and you may get different ones.

In [20]:
%%time

# For each of the 24 hours of the day, how many taxi trips there were, what was their average
# trip miles and trip total cost?
# Non-integer values should be printed with two decimal places.
df.withColumn("time_slot", date_format("TripStartTimestamp", "hh a")) \
    .groupBy("time_slot").agg({"TripMiles": "avg", "TripTotal": "avg", "*": "count"}) \
    .withColumnRenamed("count(1)", "#trips") \
    .withColumn("avg_trip_miles", format_number("avg(TripMiles)", 2)) \
    .withColumn("avg_trip_total", format_number("avg(TripTotal)", 2)) \
    .select("time_slot", "#trips", "avg_trip_miles", "avg_trip_total") \
    .cache().show(truncate=False)

+---------+------+--------------+--------------+
|time_slot|#trips|avg_trip_miles|avg_trip_total|
+---------+------+--------------+--------------+
|05 PM    |23637 |3.04          |15.16         |
|08 PM    |22218 |3.18          |15.41         |
|11 AM    |18616 |3.42          |15.41         |
|10 AM    |17775 |3.20          |15.22         |
|04 AM    |4604  |3.80          |15.19         |
|null     |48    |null          |null          |
|12 AM    |13543 |2.83          |14.08         |
|11 PM    |16299 |2.86          |14.32         |
|06 AM    |5628  |5.25          |19.92         |
|09 PM    |19783 |3.31          |15.44         |
|10 PM    |18491 |3.11          |14.95         |
|09 AM    |18246 |3.10          |14.47         |
|03 PM    |20704 |3.50          |16.26         |
|03 AM    |6594  |2.48          |12.96         |
|05 AM    |4087  |5.94          |20.94         |
|12 PM    |19873 |3.38          |15.44         |
|02 PM    |20037 |3.48          |15.99         |
|07 PM    |25400 |2.94          |14.55         |
|01 PM    |20179 |3.38          |15.54         |
|06 PM    |25444 |2.84          |14.57         |
+---------+------+--------------+--------------+
only showing top 20 rows

CPU times: user 15.6 ms, sys: 5.46 ms, total: 21.1 ms
Wall time: 3.02 s


#### 3.	(4 points) To have a rough estimation of the most popular locations for picking up clients at each moment, create and index reporting

For each of the 24 hours of the day, which are the (up to) 5 most popular routes (pairs pickup/dropoff regions) according to the the total number of taxi trips? Also report and the average fare (total trip cost).

Non-integer values should be printed with two decimal places.

Output is expected to have four columns (pickup_location, #trips, avg_trip_miles, avg_trip_total).

In [21]:
%%time

# For each of the 24 hours of the day, which are the(up to) 5 most popular routes(pairs
# pickup / dropoff regions) according to the the total number of taxi trips? Also report
# and the average fare(total trip cost).
# Non - integer values should be printed with two decimal places.

windowSpec = Window.partitionBy("hour").orderBy(col("count(1)").desc())

df.where(col("PickupRegionID").isNotNull() & col("DropoffRegionID").isNotNull()) \
    .withColumn("hour", date_format("TripStartTimestamp", "hh a")) \
    .groupBy("hour", "PickupRegionID", "DropoffRegionID").agg(
    {"TripMiles": "avg", "TripTotal": "avg", "*": "count"}) \
    .withColumn("row_number", row_number().over(windowSpec)) \
    .where("row_number <= 5") \
    .withColumnRenamed("count(1)", "#trips") \
    .withColumn("avg_trip_miles", format_number("avg(TripMiles)", 2)) \
    .withColumn("avg_trip_total", format_number("avg(TripTotal)", 2)) \
    .withColumn("pickup_location", concat_ws(" ", "hour", "PickupRegionID", "DropoffRegionID")) \
    .select("pickup_location", "#trips", "avg_trip_miles", "avg_trip_total") \
    .cache().show(truncate=False)

+-----------------------------+------+--------------+--------------+
|pickup_location              |#trips|avg_trip_miles|avg_trip_total|
+-----------------------------+------+--------------+--------------+
|05 PM 17031839100 17031839100|466   |0.58          |6.66          |
|05 PM 17031839100 17031281900|327   |0.58          |6.56          |
|05 PM 17031839100 17031320100|292   |0.69          |7.20          |
|05 PM 17031320100 17031839100|218   |0.74          |7.91          |
|05 PM 17031839100 17031280100|199   |0.67          |6.77          |
|08 PM 17031839100 17031839100|183   |0.49          |6.17          |
|08 PM 17031980000 17031980000|115   |1.86          |12.17         |
|08 PM 17031839100 17031320100|107   |0.77          |7.36          |
|08 PM 17031839100 17031081700|106   |0.69          |7.37          |
|08 PM 17031839100 17031081403|101   |1.03          |8.22          |
|11 AM 17031839100 17031839100|447   |0.66          |6.98          |
|11 AM 17031839100 17031320100|241   |0.76          |7.91          |
|11 AM 17031320100 17031839100|215   |0.85          |7.53          |
|11 AM 17031839100 17031081700|160   |0.83          |7.43          |
|11 AM 17031839100 17031081500|154   |1.02          |7.89          |
|04 AM 17031081700 17031081800|35    |0.39          |6.42          |
|04 AM 17031081700 17031081700|23    |0.89          |6.57          |
|04 AM 17031980000 17031980000|19    |0.92          |21.41         |
|04 AM 17031839100 17031980000|19    |16.84         |46.02         |
|04 AM 17031081800 17031081800|18    |0.27          |5.81          |
+-----------------------------+------+--------------+--------------+
only showing top 20 rows

CPU times: user 28.1 ms, sys: 19.2 ms, total: 47.3 ms
Wall time: 5.52 s

In [22]:
#### 4 Understanding the impact of gas price in the total trip cost

In [23]:
%%time

# https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=pet&s=emm_epm0_pte_nus_dpg&f=m
gas_df = spark.read.csv("/home/jovyan/assignment2/gas_price.csv", sep=';', inferSchema=True, header=True)
gas_df.show()

# https://sparkbyexamples.com/pyspark/pyspark-pivot-and-unpivot-dataframe
unpivotExpr = "stack(12, 'Jan',Jan,'Feb',Feb,'Mar',Mar,'Apr',Apr,'May',May,'Jun',Jun,'Jul',Jul," \
              "'Aug',Aug,'Sep',Sep,'Oct',Oct,'Nov',Nov,'Dec',Dec) as (Month,Price)"

gas_df = gas_df.select('Year', expr(unpivotExpr))
gas_df.show()
gas_df.printSchema()

gas_df = gas_df.withColumn("DateKey", concat_ws(" ", "Year", "Month"))\
    .persist(storageLevel=StorageLevel.MEMORY_ONLY)

gas_df.show()

df = df.withColumn("DateKey", date_format("TripStartTimestamp", "y LLL"))
df.show()

trips = df.alias("trips")
gas = gas_df.alias('gas')

joined = trips.join(gas, gas.DateKey == trips.DateKey)

# https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles
# United States (L/100 km) – 'combined' 9.8, 'city' 11.2, 'highway' 8.1[21]
# 26.3 mpg

agg_costs = joined.withColumn("gas_cost", joined.TripMiles * joined.Price / 26.3) \
    .groupBy(year('TripStartTimestamp').alias('year')) \
    .agg({"gas_cost": "sum", "TripTotal": "sum", "Price": "sum", "*": "count", "TripMiles": "sum"}) \
    .withColumnRenamed("sum(gas_cost)", "sum_gas_cost") \
    .withColumnRenamed("sum(TripTotal)", "sum_trip_total") \
    .withColumnRenamed("sum(TripMiles)", "sum_trip_miles") \
    .withColumnRenamed("sum(Price)", "sum_price") \
    .withColumnRenamed("count(1)", "cnt")

agg_costs.withColumn("% gas cost on total", round(agg_costs.sum_gas_cost * 100 / agg_costs.sum_trip_total, 2)) \
    .withColumn("avg gas price $/g", round(agg_costs.sum_price / agg_costs.cnt, 2)) \
    .withColumn("$/mile", round(agg_costs.sum_trip_total / agg_costs.sum_trip_miles, 2)) \
    .drop("sum_trip_total", "sum_gas_cost", "sum_price", "cnt", "sum_trip_miles") \
    .orderBy(agg_costs.year) \
    .cache().show(truncate=False)

+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|Year|  Jan|  Feb|  Mar|  Apr|  May|  Jun|  Jul|  Aug|  Sep|  Oct|  Nov|  Dec|
+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|1994|0.998|1.009|1.008|1.027|1.047|1.078|1.106|1.155|1.144|1.114|1.119|1.129|
|1995| 1.13| 1.12|1.119|1.157|1.225|1.239|1.201| 1.17|1.158|1.134|1.109|1.118|
|1996|1.137|1.136|1.183|1.275|1.324|  1.3|1.272|1.251|1.247|1.249|1.278|1.282|
|1997|1.283|1.276|1.251|1.244|1.245|1.242| 1.22|1.268|1.276|1.242|1.216|1.177|
|1998|1.132|1.096|1.064|1.077|1.105|1.103|1.094|1.065|1.049|1.059|1.036|0.987|
|1999| 0.98|0.962|1.022|1.171|1.171|1.154|1.197| 1.26|1.295|1.285|1.292|1.313|
|2000|1.329|1.415|1.556|1.506|1.526|1.666|1.591|1.506|1.588|1.571|1.557|1.483|
|2001|1.487| 1.49| 1.45|1.591|1.738|1.658|1.466|1.461|1.557|1.357|1.212|1.127|
|2002|1.148|1.155|1.289|1.439|1.434|1.424|1.438|1.438|1.441|1.486|1.461|1.429|
|2003|  1.5|1.655|1.734|1.633|1.539|1.533|1.554|1.661|1.721|1.606|1.555|1.522|
|2004|1.614| 1.69|1.778|1.839|2.023|2.013|1.954| 1.92|1.912|2.042|2.023|1.887|
|2005|1.875|1.953| 2.12|2.285|2.205|2.198|2.333|2.529|2.951|2.765|2.303|2.229|
|2006| 2.36|2.326|2.468|2.787|2.953| 2.93|3.025|2.999|2.606|2.293|2.275|2.359|
|2007|2.289|2.323|2.609|2.891|3.187|3.102|3.011|2.834|2.849|2.853|3.128| 3.07|
|2008|3.095|3.078|3.293|3.507|3.815|4.105|4.114|3.833|3.756|3.112|2.208|1.745|
|2009| 1.84|1.975|2.011|2.102|2.316|2.681|2.582| 2.67|2.609|2.605|2.706|2.663|
|2010|2.769|2.699|2.824|  2.9| 2.89|2.785|2.782|2.783|2.757|2.853|2.913|3.048|
|2011|3.148|3.264|3.615|3.852| 3.96|3.735|3.705|3.696|3.667|3.506|3.443|3.326|
|2012| 3.44| 3.64|3.907|3.958|3.791|3.596|3.498| 3.78| 3.91|3.812|3.521|3.381|
|2013|3.391|3.736|3.779|3.638|3.675|3.689|3.661|3.645|3.604| 3.42|3.322|3.357|
+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
only showing top 20 rows

+----+-----+-----+
|Year|Month|Price|
+----+-----+-----+
|1994|  Jan|0.998|
|1994|  Feb|1.009|
|1994|  Mar|1.008|
|1994|  Apr|1.027|
|1994|  May|1.047|
|1994|  Jun|1.078|
|1994|  Jul|1.106|
|1994|  Aug|1.155|
|1994|  Sep|1.144|
|1994|  Oct|1.114|
|1994|  Nov|1.119|
|1994|  Dec|1.129|
|1995|  Jan| 1.13|
|1995|  Feb| 1.12|
|1995|  Mar|1.119|
|1995|  Apr|1.157|
|1995|  May|1.225|
|1995|  Jun|1.239|
|1995|  Jul|1.201|
|1995|  Aug| 1.17|
+----+-----+-----+
only showing top 20 rows

root
 |-- Year: integer (nullable = true)
 |-- Month: string (nullable = true)
 |-- Price: double (nullable = true)

+----+-----+-----+--------+
|Year|Month|Price| DateKey|
+----+-----+-----+--------+
|1994|  Jan|0.998|1994 Jan|
|1994|  Feb|1.009|1994 Feb|
|1994|  Mar|1.008|1994 Mar|
|1994|  Apr|1.027|1994 Apr|
|1994|  May|1.047|1994 May|
|1994|  Jun|1.078|1994 Jun|
|1994|  Jul|1.106|1994 Jul|
|1994|  Aug|1.155|1994 Aug|
|1994|  Sep|1.144|1994 Sep|
|1994|  Oct|1.114|1994 Oct|
|1994|  Nov|1.119|1994 Nov|
|1994|  Dec|1.129|1994 Dec|
|1995|  Jan| 1.13|1995 Jan|
|1995|  Feb| 1.12|1995 Feb|
|1995|  Mar|1.119|1995 Mar|
|1995|  Apr|1.157|1995 Apr|
|1995|  May|1.225|1995 May|
|1995|  Jun|1.239|1995 Jun|
|1995|  Jul|1.201|1995 Jul|
|1995|  Aug| 1.17|1995 Aug|
+----+-----+-----+--------+
only showing top 20 rows

+--------------------+--------------------+-------------------+-------------------+-----------+---------+--------------+---------------+---------------+----------------+-----+----+-----+------+---------+-----------+--------------------+----------------------+-----------------------+----------------------+-----------------------+------------------------+-----------------------+--------+
|              TripID|              TaxiID| TripStartTimestamp|   TripEndTimestamp|TripSeconds|TripMiles|PickupRegionID|DropoffRegionID|PickupCommunity|DropoffCommunity| Fare|Tips|Tolls|Extras|TripTotal|PaymentType|             Company|PickupCentroidLatitude|PickupCentroidLongitude|PickupCentroidLocation|DropoffCentroidLatitude|DropoffCentroidLongitude|DropoffCentroidLocation| DateKey|
+--------------------+--------------------+-------------------+-------------------+-----------+---------+--------------+---------------+---------------+----------------+-----+----+-----+------+---------+-----------+--------------------+----------------------+-----------------------+----------------------+-----------------------+------------------------+-----------------------+--------+
|                null|                null|               null|               null|       null|     null|          null|           null|           null|            null| null|null| null|  null|     null|       null|                null|                  null|                   null|                  null|                   null|                    null|                   null|    null|
|                null|                null|               null|               null|       null|     null|          null|           null|           null|            null| null|null| null|  null|     null|       null|                null|                  null|                   null|                  null|                   null|                    null|                   null|    null|
|                null|                null|               null|               null|       null|     null|          null|           null|           null|            null| null|null| null|  null|     null|       null|                null|                  null|                   null|                  null|                   null|                    null|                   null|    null|
|                null|                null|               null|               null|       null|     null|          null|           null|           null|            null| null|null| null|  null|     null|       null|                null|                  null|                   null|                  null|                   null|                    null|                   null|    null|
|cd5c9dbebe8643548...|eadcdcce87daf0049...|2013-01-06 10:15:00|2013-01-06 10:30:00|      420.0|     3.38|          null|           null|            8.0|            48.0| 9.65| 0.0|  0.0|   0.0|     9.65|       Cash|                null|          41.899602111|          -87.633308037|  POINT (-87.633308...|           41.729676423|           -87.572717134|   POINT (-87.572717...|2013 Jan|
|0de4440454e5c6f27...|bf144d3085b875983...|2013-01-06 19:45:00|2013-01-06 19:45:00|      300.0|     0.48|   17031081402|           null|            8.0|            null| 4.65| 0.0|  0.0|   0.0|     4.65|Credit Card|                null|          41.891971508|          -87.612945414|  POINT (-87.612945...|                   null|                    null|                   null|2013 Jan|
|37f5ec45b80eaa900...|b4e899d3fb518368a...|2013-03-20 14:30:00|2013-03-20 14:30:00|      420.0|     2.15|          null|           null|           24.0|            null| 7.45| 0.0|  0.0|   0.0|     7.45|       Cash|                null|          41.901206994|          -87.676355989|  POINT (-87.676355...|                   null|                    null|                   null|2013 Mar|
|7dcef50a2d5edc804...|248103cdd73487ab0...|2013-01-09 10:30:00|2013-01-09 10:45:00|      600.0|     1.86|   17031081300|           null|            8.0|            null| 7.65| 0.0|  0.0|   0.0|     7.65|       Cash|                null|          41.898331794|          -87.620762865|  POINT (-87.620762...|                   null|                    null|                   null|2013 Jan|
|d6becc86b9a29774b...|99a94f14a88b159da...|2013-02-20 13:45:00|2013-02-20 14:00:00|      540.0|      1.8|   17031839100|    17031833000|           32.0|            28.0| 7.45| 2.0|  0.0|   1.0|    10.45|Credit Card|                null|          41.880994471|          -87.632746489|  POINT (-87.632746...|            41.88528132|             -87.6572332|   POINT (-87.657233...|2013 Feb|
|9da3e858d3ba37d9b...|f87130f757728a55c...|2013-02-04 16:45:00|2013-02-04 16:45:00|      240.0|     0.73|   17031839100|    17031833000|           32.0|            28.0| 5.05| 0.0|  0.0|   0.0|     5.05|       Cash|                null|          41.880994471|          -87.632746489|  POINT (-87.632746...|            41.88528132|             -87.6572332|   POINT (-87.657233...|2013 Feb|
|57144df9d42b41b0a...|864c0d162d3a4660d...|2013-02-03 11:45:00|2013-02-03 11:45:00|      360.0|      1.8|   17031071400|    17031081300|            7.0|             8.0| 6.85| 3.0|  0.0|   0.0|     9.85|Credit Card|                null|          41.922082541|          -87.634156093|  POINT (-87.634156...|           41.898331794|           -87.620762865|   POINT (-87.620762...|2013 Feb|
|8fc43deb474f1f8cc...|4a6999af87938af45...|2013-03-25 04:15:00|2013-03-25 04:15:00|      180.0|      0.8|          null|           null|           32.0|             8.0| 4.65| 0.0|  0.0|   0.0|     4.65|       Cash|                null|          41.878865584|          -87.625192142|  POINT (-87.625192...|           41.899602111|           -87.633308037|   POINT (-87.633308...|2013 Mar|
|95234325752dda181...|af6fed00f40ccaeab...|2013-02-15 14:45:00|2013-02-15 15:00:00|      840.0|     3.96|          null|           null|            7.0|            null|11.85| 0.0|  0.0|   0.0|    11.85|       Cash|                null|          41.922686284|          -87.649488729|  POINT (-87.649488...|                   null|                    null|                   null|2013 Feb|
|cf4315b872d950031...|248103cdd73487ab0...|2013-01-12 02:45:00|2013-01-12 02:45:00|      480.0|     1.86|   17031071100|           null|            7.0|            null| 7.05| 0.0|  0.0|   0.0|     7.05|       Cash|                null|          41.921778188|          -87.651061884|  POINT (-87.651061...|                   null|                    null|                   null|2013 Jan|
|92448faacfe9d3bab...|0156573f07d7ebbb6...|2013-01-13 02:45:00|2013-01-13 02:45:00|      480.0|     1.63|   17031062100|           null|            6.0|            null| 7.05| 3.0|  0.0|   3.0|    13.05|Credit Card|                null|          41.942691844|          -87.651770507|  POINT (-87.651770...|                   null|                    null|                   null|2013 Jan|
|69cca5fc10c0d186a...|13c0599d1bce4a623...|2013-04-28 18:45:00|2013-04-28 19:00:00|      300.0|      2.3|          null|           null|            3.0|             3.0| 7.65| 2.0|  0.0|   1.0|    10.65|Credit Card|                null|           41.96581197|          -87.655878786|  POINT (-87.655878...|            41.96581197|           -87.655878786|   POINT (-87.655878...|2013 Apr|
|c96b05b04d6f74302...|9bd591de3c69a1ea8...|2013-03-23 19:45:00|2013-03-23 19:45:00|      360.0|      1.1|   17031081202|           null|            8.0|            null| 6.05| 0.0|  0.0|   1.0|     7.05|       Cash|                null|          41.902788048|           -87.62614559|  POINT (-87.626145...|                   null|                    null|                   null|2013 Mar|
|668997fb83ab4537a...|cbd9c477ea0af6c70...|2014-09-24 15:15:00|2014-09-24 15:15:00|        0.0|      0.0|          null|           null|           null|            null| 5.85|0.88|  0.0|   0.0|     6.73|Credit Card|Chicago Elite Cab...|                  null|                   null|                  null|                   null|                    null|                   null|2014 Sep|
|cf8e4639ff76eb864...|331363e95332ae553...|2013-01-24 06:45:00|2013-01-24 06:45:00|      600.0|      2.2|   17031280100|    17031842200|           28.0|             8.0| 8.44| 0.0|  0.0|   0.0|     8.44|       Cash|                null|          41.885300022|          -87.642808466|  POINT (-87.642808...|           41.904935302|           -87.649907226|   POINT (-87.649907...|2013 Jan|
|5224d3aa08b402cfd...|bf144d3085b875983...|2013-01-01 18:30:00|2013-01-01 18:30:00|      360.0|     1.61|   17031081403|           null|            8.0|            null| 6.65| 0.0|  0.0|   1.5|     8.15|       Cash|                null|          41.890922026|          -87.618868355|  POINT (-87.618868...|                   null|                    null|                   null|2013 Jan|
+--------------------+--------------------+-------------------+-------------------+-----------+---------+--------------+---------------+---------------+----------------+-----+----+-----+------+---------+-----------+--------------------+----------------------+-----------------------+----------------------+-----------------------+------------------------+-----------------------+--------+
only showing top 20 rows

+----+-------------------+-----------------+------+
|year|% gas cost on total|avg gas price $/g|$/mile|
+----+-------------------+-----------------+------+
|2013|2.2                |3.57             |6.17  |
|2014|2.68               |3.46             |4.9   |
|2015|2.06               |2.53             |4.68  |
|2016|2.02               |2.25             |4.26  |
|2017|2.19               |2.53             |4.38  |
|2018|2.37               |2.83             |4.54  |
|2019|2.18               |2.69             |4.72  |
|2020|1.98               |2.47             |4.7   |
+----+-------------------+-----------------+------+

CPU times: user 44.9 ms, sys: 12.2 ms, total: 57.1 ms
Wall time: 7.44 s

In [24]:
spark.stop()